name: Publish Docker image to Azure Container Registry

on:
  release:
    types: [published]

jobs:
  push_to_acr:
    name: Push Docker image to Azure Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          registry: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/health-center

      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
